spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: //192.168.1.12/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
logging:
#  pattern:
#    console: "%d - %msg%n"
  file:
    path: /var/log/tomcat/
  #level:
    #root: debug
    #com.stan.springboottrading.LoggerTest: debug